### ISSUE TITLE
Wiki에 이미지 등록하기

### ISSUE THREAD

**Issue by L2zz** [18-2-SKKU-OSS/2018-2-OSS-L5#1]
Wiki에 이미지 등록하기 위해서는 URL를 입력해야 하는데 
어떤 URL을 입력해야하는지 모르겠네요

**Comment by ddjddd** [comment]
Repository 의 이미지 링크 올리는 것으로 알고있어요.
마크다운 양식(Readme.md) 작성할때 이미지 첨부하는 것처럼 링크 올리면 첨부되는걸로 알고있습니다.

**Comment by L2zz** [comment]
아 감사합니다!
