### ISSUE TITLE
Translation Style Guide Rule 결정

### ISSUE THREAD

**Issue by L2zz** [18-2-SKKU-OSS/2018-2-OSS-L5#11]
본격적인 번역작업에 앞서 번역작업의 전반적인 규칙을 규정하는 Translation Style Guide의 Rule항목이 구체화 되어야 한다고 생각됩니다.

이에 대해 추가 해야할 Rule이 있다면 자유롭게 의견 제시해 주세요!

**Comment by L2zz** [comment]
Rule을 제외한 항목들에 대해서는 하위 항목을 알파벳 순서로 채워나갔으면 합니다.

**Comment by L2zz** [comment]
복수와 단수를 구분하지 않고 모두 단수로 번역하면 좋을 것 같습니다.

**Comment by L2zz** [comment]
특수 기호 사용에 대해서는 원문의 모양을 따르는 것이 좋을 것 같습니다.

**Comment by measo3** [comment]
다나까로 사용하는 건 어떨까요 끝나는 말을?

**Comment by NohYeonJeong** [comment]
동의합니다. 알파벳 순서로 sorting하면 가독성이 더 좋을 것 같습니다.

**Comment by NohYeonJeong** [comment]
경어체 '~합니다' 가 좋을 것 같습니다.

**Comment by eunjeung** [comment]
번역 가이드를 참고해서 하는게 좋을 것 같아요 
https://zulip.readthedocs.io/en/stable/translating/translating.html#translation-style-guides

번역 하다보면 변수나 HTML 코드를 번역하지 말라는 항목이 있습니다.
참고하시기 바랍니다.

**Comment by L2zz** [comment]
Term에 대해서는
1. 어떻게 번역할지 
2. 용례 
3. discussion log
를 기록하면 좋을 것 같습니다.

**Comment by measo3** [comment]
문장부호 (. , ! ?)등 이 있으면 다나까로 끝나는걸로 하면 좋을 것 같습니다.

**Comment by eunjeung** [comment]
you를 뭐라고 번역하는 것이 좋을까요?

**Comment by eunjeung** [comment]
수 표현의 띄어쓰기
띄어쓰는 것이 원칙이나 붙여쓰는 것도 가능하다. 따라서 zulip의 원문을 따라 띄어쓰기를 하는 것으로 결정한다.

**Comment by eunjeung** [comment]
you는 귀하로 통일하여 작성합니다
