### ISSUE TITLE
Wiki에 번역 작업 workflow 등록

### ISSUE THREAD

**Issue by L2zz** [18-2-SKKU-OSS/2018-2-OSS-L5#12]
Zulip 번역 작업 workflow를 그림으로 작성하여 등록하였습니다.

**Comment by measo3** [comment]
![image](https://user-images.githubusercontent.com/43779940/49435141-3ac97a00-f7f9-11e8-9e9a-e746bb6a17f2.png)

위의 화면의 부분들만 캡쳐해서 올려주세요!
