### ISSUE TITLE
[Terms] organization 번역

### ISSUE THREAD

**Issue by L2zz** [18-2-SKKU-OSS/2018-2-OSS-L5#13]
기존 번역은 단체와 조직이 혼용되고 있습니다. 
어떤 번역이 더 적합할까요?

**Comment by L2zz** [comment]
Facebook에서는 기관으로 번역하고 있습니다.

**Comment by L2zz** [comment]
Google에서는 조직으로 번역하고 있습니다.
https://cloud.google.com/resource-manager/docs/creating-managing-organization

**Comment by eunjeung** [comment]
제 생각은 기관보다 조직이 더 알맞을 것 같다는 생각이 드네요 다른분들 생각은 어떠신가요?

**Comment by NohYeonJeong** [comment]
저도 기관보다 조직이라고 번역하는 것이 알맞다고 생각합니다.

**Comment by measo3** [comment]
조직이 가장 보편적으로 통용되는걸로 알고 있습니다.

**Comment by L2zz** [comment]
조직으로 번역하겠습니다!
