### ISSUE TITLE
[Terms] history 번역

### ISSUE THREAD

**Issue by L2zz** [18-2-SKKU-OSS/2018-2-OSS-L5#14]
기존에 기록과 이력이 혼용되고 있습니다.
어떤 번역이 더 적합할까요?

**Comment by L2zz** [comment]
Google에서는 사용 기록으로 번역합니다.

**Comment by L2zz** [comment]
Youtube에서는 기록으로 번역합니다.

**Comment by eunjeung** [comment]
이 경우는 오늘 논의해보는게 좋겠습니다

**Comment by measo3** [comment]
기록으로 통일하는건 어떨까요

**Comment by ddjddd** [comment]
내역이라는 단어는 어떤가요

**Comment by eunjeung** [comment]
기록이 낫지 않을까요? 채팅 프로그램이니까 이력과는 맞지 않는 것 같아요

**Comment by NohYeonJeong** [comment]
기록이라는 단어가 좋을 것 같습니다.

**Comment by L2zz** [comment]
그러면 후보가 다음과 같이 나왔습니다.
 
1. 기록
2. 이력
3. 내역

최종적으로 결정할 단어를 선택해주세요!

**Comment by NohYeonJeong** [comment]
1

**Comment by L2zz** [comment]
1. 기록

**Comment by measo3** [comment]
1번이 좋은것 같습니다

**Comment by eunjeung** [comment]
기록이 좋을 것 같아요 :)

**Comment by L2zz** [comment]
만장일치로 기록이 선택되었습니다. 

history는 '기록'으로 번역하기로 합시다.
