### ISSUE TITLE
Fork 이후 작업과정

### ISSUE THREAD

**Issue by L2zz** [18-2-SKKU-OSS/2018-2-OSS-L5#17]
Fork한 후 각자 본인의 branch를 생성하여 작업 후 merge하도록 합시다.

**Comment by eunjeung** [comment]
각자 사용하는 branch 이름을 여기다 쓰는것이 좋을 것 같아요 :)
저는 eunjeung 입니다.

**Comment by L2zz** [comment]
저는 l2zz 입니다.

**Comment by measo3** [comment]
저는 measo3입니다.

**Comment by NohYeonJeong** [comment]
저는 NohYeonJeong입니다!

**Comment by ddjddd** [comment]
jinho 로 만들게요
