### ISSUE TITLE
Review 방법 아시는 분 계신가요

### ISSUE THREAD

**Issue by eunjeung** [18-2-SKKU-OSS/2018-2-OSS-L5#18]
방금 Unreviewed 항목에서 Review를 실행하였는데 여전히 Unreviewed 항목에 떠있네요
혹시 이 방법에 대해 아시는 분 계신가요?

-

**Comment by eunjeung** [comment]
Korean 쪽에는 Review 제도가 활성화되지 않은 것 같습니다.

**Comment by ddjddd** [comment]
그럼 우선, 자체적으로 issue를 통해서 reviw를 진행하는게 좋을 것 같네요
