### ISSUE TITLE
번역 컨텐츠 우선도 및 파트 정하기

### ISSUE THREAD

**Issue by L2zz** [18-2-SKKU-OSS/2018-2-OSS-L5#2]
번역 작업을 진행 하기 전 결정사항을 논의하려 합니다.

1. 우선적으로 작업할 컨텐츠
2. 개인 별 번역 파트

11월 28일 오후 10시에 카톡으로 미팅을 진행하고자 하니
그 전까지 Transifex에 들어가 내용을 확인해봐 주세요~

**Comment by ddjddd** [comment]
넵 👍

**Comment by eunjeung** [comment]
넵 알겠습니다 :)
