### ISSUE TITLE
[info] 와 같은 줄임말에 대해..

### ISSUE THREAD

**Issue by measo3** [18-2-SKKU-OSS/2018-2-OSS-L5#20]
[info] 등과 같은 줄임말은 알아서 information으로 알고 번역하는게 맞을까요?

**Comment by eunjeung** [comment]
정보라고 번역하는 것이 좋을 것 같네요

**Comment by L2zz** [comment]
넵 원 단어를 토대로 번역하면 좋을 것 같습니다.
