### ISSUE TITLE
email copied -> 과거분사가 온거면 수동의 의미인가요

### ISSUE THREAD

**Issue by measo3** [18-2-SKKU-OSS/2018-2-OSS-L5#21]
복사된 이메일인가요 이메일 복사인가요?

**Comment by L2zz** [comment]
복사된 이메일이라면 Copied email 했을 것 같아서 email copied면 이메일이 복사된 상황에 쓰일 것 같기나네요 한번 소스코드를 확인해 봐야할 것 같습니다

**Comment by ddjddd** [comment]
'이메일 복사됨' 정도로 해석 가능하지 않을까 생각합니다!

**Comment by NohYeonJeong** [comment]
진호님 동의합니다.
