### ISSUE TITLE
저희 Wiki에 활동 내역 올릴때..!

### ISSUE THREAD

**Issue by measo3** [18-2-SKKU-OSS/2018-2-OSS-L5#22]
![image](https://user-images.githubusercontent.com/43779940/49435247-84b26000-f7f9-11e8-8879-551d26130185.png)

위키에 활동 내역 올리실 때 이 부분만 캡쳐해주시면 됩니다.!

**Comment by L2zz** [comment]
넵 감사합니다! :blush:

**Comment by NohYeonJeong** [comment]
네 감사합니다!

**Comment by NohYeonJeong** [comment]
저 캡쳐에서는 아직 번역되지 않은 문장들도 나오는데, translator에서 검색하여 자신이 번역한 문장들만 올리면 될까요?

**Comment by measo3** [comment]
네 맞습니당
