### ISSUE TITLE
추가 된 Rule확인 

### ISSUE THREAD

**Issue by L2zz** [18-2-SKKU-OSS/2018-2-OSS-L5#23]
결정된 Rule에 대해서는 rule branch를 만들어 놓을테니 필요시 참고해주세요!

**Comment by L2zz** [comment]
rule branch로 작성하니 여러가지로 번거로운 점이 많아서 제 브랜치에서 확인해 주세요
혹시 불편하시다면 말씀해 주세요!

**Comment by NohYeonJeong** [comment]
감사합니다.
