### ISSUE TITLE
번역 스타일 가이드 부재

### ISSUE THREAD

**Issue by L2zz** [18-2-SKKU-OSS/2018-2-OSS-L5#3]
Translation Guideline을 따르면 번역 시작 시에 style guide를 작성하는 것이 추천되고 있습니다.

하지만 한국어 번역작업은 이미 상당 부분 진행됐음에도 style guide가 존재하지 않는데요.

이 부분에 대해서 저는 저희가 style guide를 작성해도 되는가 물어보고 싶은데 
다른 분들은 어떻게 생각하시나요?

**Comment by eunjeung** [comment]
좋은 의견인것 같습니다.
