### ISSUE TITLE
[Terms] linkifier 번역

### ISSUE THREAD

**Issue by L2zz** [18-2-SKKU-OSS/2018-2-OSS-L5#31]
linkifier는 내부에서 지정한 패턴을 통해 website와 연결해 줍니다.
예를 들어 다음과 같이 linkfier를 설정하고
![linkifier](https://user-images.githubusercontent.com/37107066/49508372-e6400080-f8c5-11e8-895c-7ee6bd9e409d.PNG)

다음 사진 처럼 스트림에 메시지를 작성했을 때
![test_link](https://user-images.githubusercontent.com/37107066/49508418-01ab0b80-f8c6-11e8-9d49-3a4f8f7aa5f2.PNG)
`https://github.com/18-2-SKKU-OSS/2018-2-OSS-L5/issues/11`로 연결해 줍니다.

이러한 기능을 하는 linkifier를 어떻게 번역해야할까요?

**Comment by ddjddd** [comment]
링크를 걸어주는 역할이니 링커 어떤가요

혹은 링크 변환기?

**Comment by NohYeonJeong** [comment]
저는 단순하게 연결고리라고 변역했는데 링커로 바꿔야 할까요?

**Comment by measo3** [comment]
문맥적으로는 링커가 제일 나아보이네요!

**Comment by eunjeung** [comment]
저는 링크 변환기가 좀 더 나을 것 같네요

**Comment by L2zz** [comment]
고유 명사니까 조금더 풀어쓰면서 직관성이 있는
링크 변환기 사용하겠습니다
