### ISSUE TITLE
[Other] user & member

### ISSUE THREAD

**Issue by L2zz** [18-2-SKKU-OSS/2018-2-OSS-L5#32]
user는 사용자로 member는 회원으로 지금까지 번역되어 있는데
Zulip 내부에서 그 쓰임이 비슷합니다. 
이를 이전처럼 구분하여 번역할지 통일할지 의견을 내주세요

**Comment by ddjddd** [comment]
user 는 zulip사용자 전체를 말하는 것 같고, member는 특히 스트림에 포함된 사람을 의미하는 것 같네요. 
member can invite other users 이런 표현이 있는걸로 봐서는 구분해서 쓰는것이 맞지 않을까요?

**Comment by NohYeonJeong** [comment]
진호님 동의합니다.

**Comment by L2zz** [comment]
넵 그러면 구분하여 사용하도록 하겠습니다.
