### ISSUE TITLE
[Phrases] Avatar from Gravatar

### ISSUE THREAD

**Issue by L2zz** [18-2-SKKU-OSS/2018-2-OSS-L5#33]
아바타 설정에 나와있는 
`Avatar from Gravatar` 를 `Gravatar에서 아바타 가져오기`로 해석 했는데 괜찮은가요?

**Comment by NohYeonJeong** [comment]
네 괜찮은 것 같습니다.

**Comment by L2zz** [comment]
넵 그러면 유지하도록 하겠습니다.

**Comment by ddjddd** [comment]
넵 그대로 유지해도 될것 같네요

**Comment by L2zz** [comment]
유지 하겠습니다!
