### ISSUE TITLE
[Terms]  stream permissions 

### ISSUE THREAD

**Issue by L2zz** [18-2-SKKU-OSS/2018-2-OSS-L5#34]
https://zulipchat.com/help/stream-permissions 
stream permissions 은 stream의 프라이버시 설정을 변경하여 
대상 유저들의 권한을 변경합니다.

번역으로는 승인, 허락, 허가 등으로 번역되는데 자연스러운게 표현이 없을까요?

**Comment by ddjddd** [comment]
일반적으로 그냥 '권한'으로 많이 사용하는 것 같네요

**Comment by ddjddd** [comment]
![image](https://user-images.githubusercontent.com/26399087/49569508-7e49f280-f977-11e8-80e5-c5ead58fbbf2.png)

이것도 이전 사용자가 '권한'을 사용해서 그대로 가는게 맞지 않을까요?

**Comment by L2zz** [comment]
넵 권한으로 사용하도록 하겠습니다.

**Comment by L2zz** [comment]
Permission을 통해 권한을 부여한다고 생각할 수 있어서 권한도 괜찮은 것 같네요!

**Comment by L2zz** [comment]
저 예시들은 허가범위에 따른 권한을 나타내는 것 같은데

`Change stream permissions for #` 
steam 내부의 사용자 권한을 변경 하는 것같아서 번역 문장의 주체가 스트림인 만큼 `권한` 보다는 `허가`가 적합해 보이는데  다른 분들은 어떠신가요?

**Comment by measo3** [comment]
저는 권한이 자연스러운거 같아요! 스트림의 권한도 어색하지 않은거 같네요!

**Comment by eunjeung** [comment]
권한이 좀 더 자연스럽지 않나요? stream 내부의 사용자 권한을 변경하는 것이니까요

**Comment by L2zz** [comment]
권한이 자연스럽다면 권한으로 해석하도록 할게요~
