### ISSUE TITLE
[Review] Click outside the input box to save. We\'ll automatically notify anyone that was added or removed.

### ISSUE THREAD

**Issue by L2zz** [18-2-SKKU-OSS/2018-2-OSS-L5#35]
`Click outside the input box to save. We\'ll automatically notify anyone that was added or removed.` 
`입력란 밖을 클릭하여 저장합니다. 추가되거나 제거된 사람에게는 자동으로 알려줍니다.`
제시된 문자을 이처럼 해석했는데 자연스러운 가요?

**Comment by NohYeonJeong** [comment]
괜찮은것 같습니다.

**Comment by L2zz** [comment]
넵 유지하도록 하겠습니다.

**Comment by measo3** [comment]
괜찮은 것 같습니다

**Comment by L2zz** [comment]
유지하겠습니다!
