### ISSUE TITLE
[Review] Domain for your G Suite team (required)

### ISSUE THREAD

**Issue by L2zz** [18-2-SKKU-OSS/2018-2-OSS-L5#36]
`Domain for your G Suite team (required)`
`당신의 G Suite team을 위한 도메인 (필요됨)`
이렇게 번역하였는데 저 required가 무엇을 수식하는지 확실하지 않습니다.

**Comment by NohYeonJeong** [comment]
무엇을 수식한다기 보다는 '당신의 G Suite team을 위한 도메인'이 필수사항이라는 것을 의미하는거 같습니다. (필수) 이렇게 번역하면 될 것 같아요.

**Comment by measo3** [comment]
요구된 사항정도라고 생각하시면 될거 같네요. 요구사항 정도

**Comment by eunjeung** [comment]
필수 사항? 이 적합할 것 같아요

**Comment by L2zz** [comment]
그런 의미라면 (필수) 사용하겠습니다!
