### ISSUE TITLE
[Terms] generic bots

### ISSUE THREAD

**Issue by L2zz** [18-2-SKKU-OSS/2018-2-OSS-L5#37]
generic bots은 들여오고 내보내는 web hook을 모두 수행하는 봇을 의미하는 것 같습니다.
그래서 `범용 봇`으로 해석하고자 하는데 괜찮은가요?

**Comment by ddjddd** [comment]
넵 딱히 대체할 말이 없을것 같네요

**Comment by ddjddd** [comment]
![image](https://user-images.githubusercontent.com/26399087/49568177-961f7780-f973-11e8-9b64-107769f5e6ea.png)

기존에 활동하시던 번역자 분이 '일반 봇' 으로 칭하는데 이를 따라가야 할 것 같습니다.

**Comment by L2zz** [comment]
앗 저도 확인은 했었는데 일반 봇이 직관성이 떨어진다고 생각이 들어서요

**Comment by measo3** [comment]
그런데 generic bot 이라는 말 자체가 원래 직관성이 좀 떨어져 보여서 일반 봇도 나쁘지 않아보여요 저도 좀 그 단어가 생소하네요

**Comment by eunjeung** [comment]
이건 좀 애매하네요 ... 단어 자체가 생소해서 무엇으로 해도 괜찮을 것 같아요

**Comment by eunjeung** [comment]
일반 봇이 좀 그러면 일반적인 봇? 은 어떤가요

**Comment by L2zz** [comment]
이거 저 일반 봇이 normal로 해석되는거 같아서 
모든 용도에 사용가능하다는 범용이 더 적합하게 느껴지는 것 같습니다.

**Comment by NohYeonJeong** [comment]
저도 범용 봇 괜찮은거 같아요!

**Comment by measo3** [comment]
맞는거 같아요 일반 봇!

**Comment by L2zz** [comment]
흠,, 거의 무관한듯 하니 범용 봇 사용할게요!
