### ISSUE TITLE
[Tip] 번역 문장 수 파악하기

### ISSUE THREAD

**Issue by L2zz** [18-2-SKKU-OSS/2018-2-OSS-L5#38]
![image](https://user-images.githubusercontent.com/37107066/49513174-70429600-f8d3-11e8-85f0-e0b2d13ab8c2.png)
번역자 선택후 필터 옆 칸을 체크하시면 번역 문장 수를 파악할 수 있습니다.

**Comment by ddjddd** [comment]
확인했습니다!

**Comment by NohYeonJeong** [comment]
확인했습니다.

**Comment by measo3** [comment]
넵 알겠습니다.

**Comment by eunjeung** [comment]
확인했습니다 :)
