### ISSUE TITLE
[Terms] Non-administartor users 번역

### ISSUE THREAD

**Issue by ddjddd** [18-2-SKKU-OSS/2018-2-OSS-L5#39]
Non-administartor users

1. 비관리자 사용자
2. 관리자가 아닌 사용자 

어느 쪽이 적절할까요?

**Comment by eunjeung** [comment]
관리자가 아닌 사용자가 적절할 것 같아요

**Comment by L2zz** [comment]
관리자가 아닌 사용자가 좋아보입니다!

**Comment by ddjddd** [comment]
넵 '관리자가 아닌 사용자' 사용하겠습니다.

**Comment by ddjddd** [comment]
커스텀 이모티콘을 추가하는 사용자
