### ISSUE TITLE
Wiki 번역 내역 기록 방안 선정

### ISSUE THREAD

**Issue by L2zz** [18-2-SKKU-OSS/2018-2-OSS-L5#4]
번역작업이 파일단위가 아닌 문장단위로 이루어지기 때문에 

저희 활동 내역 관리또한 파일 단위 번역과는 다르게 이루어 져야된다고 생각합니다.

혹시 의견있으시다면 자유롭게 내주세요~

**Comment by L2zz** [comment]
Transifex 내부에 존재하는 번역자 별 검색을 통해 번역한 문장 목록과 그 수를 파악할 수 있으니 그것을 참조하는 게 방법이 될 수 있다고 생각합니다.

**Comment by ddjddd** [comment]
Transifex 내부에서 로그를 가져올 수 는 없나요?

**Comment by measo3** [comment]
지훈씨가 말씀하신거 이따가 수업시간에 말씀해주세요 번역한 문장 목록정도는 가져오는게 좋을 것 같아요

**Comment by eunjeung** [comment]
번역자 별 검색을 통해 확인할 수 있다면 그 편이 좋겠네요. 근데 만일의 경우를 위해서 교수님께 이렇게 진행을 해도 되는지 확인 작업이 필요할 것 같아요

**Comment by measo3** [comment]
교수님이 말씀하신 내용은 캡쳐나 그냥 문장을 복사해 오시면 된다고 하셨습니다. 이대로 진행하면 될 것 같습니다.

**Comment by L2zz** [comment]
Wiki에 개인 별 활동 내역 페이지 생성하여 기록하도록 합시다.

**Comment by NohYeonJeong** [comment]
네 확인했습니다!

**Comment by measo3** [comment]
넵 알겠습니다
