### ISSUE TITLE
[Terms] Up to

### ISSUE THREAD

**Issue by ddjddd** [18-2-SKKU-OSS/2018-2-OSS-L5#40]
![image](https://user-images.githubusercontent.com/26399087/49567897-7cc9fb80-f972-11e8-8f44-722ae172d1d7.png)

우선 이렇게 번역했는데 맞을까요?

**Comment by measo3** [comment]
네 괜찮은거 같아요

**Comment by eunjeung** [comment]
네 맞는 것 같습니다

**Comment by ddjddd** [comment]
그대로 ~ 까지로 사용하겠습니다.
