### ISSUE TITLE
be subscribed to stream 해석

### ISSUE THREAD

**Issue by NohYeonJeong** [18-2-SKKU-OSS/2018-2-OSS-L5#41]
이미 번역된 문장들 중에 '스트림을 구독하다'로 번역된 것들이 많던데 '가입하다'가 더 적당하지 않을까요?

**Comment by measo3** [comment]
subscribe말씀이신가요? 이건 원래 구독이 맞는걸로 알고있습니다.

**Comment by ddjddd** [comment]
기존에 구독이라는 단어를 사용하더라구요

**Comment by eunjeung** [comment]
그럼 subscribe 는 구독으로 번역하는 것으로 결정난건가요?

**Comment by measo3** [comment]
네네 !
