### ISSUE TITLE
조장님 이거 파일 캡쳐해서 올리는 방법..

### ISSUE THREAD

**Issue by measo3** [18-2-SKKU-OSS/2018-2-OSS-L5#42]
아무리 찾아봐도 안나오네요 ㅠㅠㅠ 어떻게 올리는걸까요 오른쪽 메뉴 보고 눌렀는데 어떻게 사진을 붙이는지 모르겠어요

**Comment by ddjddd** [comment]
여기 사진을 올리는 거라면 클립보드 ctrl cv 만으로 올릴수 있어요

**Comment by L2zz** [comment]
위키 사진을 올리는거는 
1.이슈탭을 하나 생성해두시고 
2.이슈탭에 사진 올리면 뜨는 링크를 위키탭으로 복사
하시면 됩니다!

**Comment by measo3** [comment]
아 제가말하는건 위키 사진올리는겁니다. 링크를 위키탭으로 복사하라구요??
