### ISSUE TITLE
[Phrases] Who can add custom emoji

### ISSUE THREAD

**Issue by L2zz** [18-2-SKKU-OSS/2018-2-OSS-L5#44]
Who can add custom emoji라는 표현은
https://zulipchat.com/help/only-allow-admins-to-add-emoji
에 나온 설명과 같이 보면
설정에서 custom emoji를 추가할 수 있는 사람을 정하는 것 같습니다.

그래서
`누가 custom emoji를 추가할 수 있습니까` 라는 의문문 보다는
`사용자 지정 이모티콘을 추가할 수 있는 사람`정도로 해석이 자연스러운 것 같은데 어떻게 생각하시나요?
밑의 표현으로 해석한다면 `who`를 조금 더 자연스럽게 해석할 방안이 있을지 의견을 듣고 싶습니다.

**Comment by NohYeonJeong** [comment]
'사용자 지정 이모티콘을 추가할 수 있는 사람'으로 리뷰하면 될거같아요!

**Comment by measo3** [comment]
커스텀 이모티콘을 추가하는 사용자는 어떨까요

**Comment by eunjeung** [comment]
사용자 지정 이모티콘을 추가할 수 있는 사람이 적절할 것 같아요 :)

**Comment by L2zz** [comment]
사용자 지정 이모티콘을 추가할 수 있는 사람 사용하겠습니다!
