### ISSUE TITLE
[Phrases] Change stream permissions for #

### ISSUE THREAD

**Issue by L2zz** [18-2-SKKU-OSS/2018-2-OSS-L5#45]
이런 형식의 문장의 경우
![image](https://user-images.githubusercontent.com/37107066/49628544-0a1b5780-fa28-11e8-8620-d4927ab78547.png)
이처럼 뒤에 따라오는 것들이 존재 하는데 이게 알아서 #뒤에 붙는지 잘모르겠네요

**Comment by NohYeonJeong** [comment]
#announce면 보통 announce의 수로 번역하면 될까요?

**Comment by L2zz** [comment]
아 저게 announce 스트림 말하는거에요

**Comment by L2zz** [comment]
traslation 스트림은 #translation이렇게 나타납니다

**Comment by L2zz** [comment]
`Change stream permissions for #` 번역문장은 이렇게 되고
프로그램에서 위처럼 나타납니다

**Comment by ddjddd** [comment]
#의 권한 변경 이런식으로 번역 되려나요

**Comment by eunjeung** [comment]
그러면 번역하면 안되지 않을까요 # 전까지만 번역하는게 나을것같은데

**Comment by L2zz** [comment]
#의 권한 변경 이렇게 해석하면 
#의 권한 변경 announce이렇게 나올 것 같아서요 ㅜ

**Comment by NohYeonJeong** [comment]
아하 # 전까지만 번역하면 될거같아요.

**Comment by ddjddd** [comment]
권한 변경, # ~

이런식으로 콤마 하나만 붙여도 될거 같아요

**Comment by L2zz** [comment]
넵넵 그러면 #의 위치는 두고 번역 하겠습니다!
