### ISSUE TITLE
[Phrases] Narrow to

### ISSUE THREAD

**Issue by L2zz** [18-2-SKKU-OSS/2018-2-OSS-L5#46]
`한정해서 보기`와 `범위 좁히기`가 혼재하는데
저는 한정해서 보기가 더 적합해 보이는데 다른분들은 어떠신가요?

**Comment by NohYeonJeong** [comment]
한정해서 보기가 더 적합해 보입니다!

**Comment by measo3** [comment]
한정해서 보기도 조금 어색한데 흠.. 더 좋은 의견 있을까요?

**Comment by ddjddd** [comment]
좁혀서 보기?...

**Comment by eunjeung** [comment]
한정해서 보기가 괜찮을 것 같아요

**Comment by L2zz** [comment]
ㅎㅎㅎ 다 한국말에서는 어색한 표현인 것 같긴하네여

**Comment by L2zz** [comment]
아니면 `~만 보기`는 어떠신가요?

**Comment by NohYeonJeong** [comment]
오 괜찮은거 같아요.

**Comment by ddjddd** [comment]
정확히 어떤 맥락에서 사용되는지를 모르겠네요

**Comment by measo3** [comment]
음.. ~만 보기가 더 나아 보이긴하네요 근데 저두 윗분과 의견은  동의합니다 맥락이 중요한거같아요

**Comment by L2zz** [comment]
![image](https://user-images.githubusercontent.com/37107066/49686505-d4b25f00-fb38-11e8-9612-cfde0b102f3d.png)

**Comment by L2zz** [comment]
이렇게 필터링 시키는 기능과 유사한 상황인 것 같습니다

**Comment by ddjddd** [comment]
~만 보기가 제일 좋겠네요

**Comment by eunjeung** [comment]
오오 ~만 보기 괜찮은 것 같아요

**Comment by measo3** [comment]
저두 ~만 보기가 제일 나아보이네요

**Comment by L2zz** [comment]
~만 보기 사용 하겠습니다!

**Comment by L2zz** [comment]
narrow by 와 같은 표현이 존재해서 이와 통일성을 맞추기 위해선 한정해서 보기로 사용해야할 것 같네요 ㅜ
