### ISSUE TITLE
[Terms] mute/unmute

### ISSUE THREAD

**Issue by L2zz** [18-2-SKKU-OSS/2018-2-OSS-L5#47]
`mute/unmute`가 `숨김/숨김해제`로 해석되는 데
스트림 또는 주제에 대해서 메시지 알림을 보내지 않는 것을 설정하는 걸로 보았을 때
`소식끄기` 정도가 더 직관성이 있어 보입니다. 다른 분들은 어떻게 생각하시나요?

**Comment by eunjeung** [comment]
알림 끄기?는 어떨까요

**Comment by L2zz** [comment]
알림끄기와 동시에 해당 주제와 스트림의 메시지도 보여지지 않게 되서 단순히 알림이라고 하기가 조금 애매한 것 같아요 ㅠ

**Comment by eunjeung** [comment]
개인적인 생각이지만 뮤트하기 언뮤트하기 그대로 사용해도 나쁘지 않을 것 같다는 생각이 듭니다 트위터의 경우에도 그대로 사용하고 있습니다

**Comment by L2zz** [comment]
오오 좋은 의견 같습니당

**Comment by measo3** [comment]
저는 mute가 정확히 무슨의미인지 몰라서 찾아봤는데 뮤트 언뮤트로 그냥 따라가는것도 좋아 보이네요 한글은 의미가 좀 어색하더라구요

**Comment by ddjddd** [comment]
![image](https://user-images.githubusercontent.com/26399087/49686435-db8ca200-fb37-11e8-9f69-935aae7a1627.png)

**Comment by ddjddd** [comment]
이미 숨기기 사용하고 있더라구요

**Comment by L2zz** [comment]
숨기기라고 해석되는데 저거 안숨겨져요ㅜ

**Comment by ddjddd** [comment]
알림 on/off 정도로 순화해서 사용하는게 어떤가요

**Comment by measo3** [comment]
알림이라는 경우에 해당이 안되는 경우가 있으면 알림도 쓰기 힘들거같아요

**Comment by L2zz** [comment]
흠 메시지를 전체로 확인 할 수 있는 곳에서 메시지를 안보이게 하는거는 알림이랑은 조금 다른거 같네여

**Comment by measo3** [comment]
뮤트 언뮤트 하고 사용자가 자의로 해석하는 방향이 좋은거 같아요

**Comment by eunjeung** [comment]
제 생각도 그렇습니다 뮤트 / 언뮤트 라고 하고 사용자가 알아서 해석하는 쪽이 나을 것 같아요

**Comment by ddjddd** [comment]
넵 동의합니다:)

**Comment by L2zz** [comment]
그러면 
이미 뮤트/언뮤트가 사용되는 표현이란느점 
알림 단어로 표현하기에는 알림이 너무 지협적인 표현이라는점을 근거로 들어
뮤트 /언뮤트 사용할게요!
