### ISSUE TITLE
[Phrases] in Zulip

### ISSUE THREAD

**Issue by L2zz** [18-2-SKKU-OSS/2018-2-OSS-L5#49]
`Streams in Zulip` 과 같은 표현에 대해서 
`Zulip 내의 스트림` 
`Zulip에 있는 스트림`
두가지 표현정도가 생각 나는데 어떤 표현이 괜찮은가요?

**Comment by eunjeung** [comment]
Zulip 내의 스트림이 괜찮은 것 같네요

**Comment by L2zz** [comment]
내의 사용하겠습니다
