### ISSUE TITLE
Translation Style Guide 작성 작업 승인과 이후 일정에 관한 논의

### ISSUE THREAD

**Issue by L2zz** [18-2-SKKU-OSS/2018-2-OSS-L5#5]
어제 말씀드린 Style guide 작성에 대해서 개발팀에 문의를 넣었고 다음처럼 승인 응답이 왔습니다.

![image](https://user-images.githubusercontent.com/37107066/49202010-7d004f00-f3e6-11e8-8f72-713f0858c743.png)

 그런데 Style guide 작성이 제 생각에 분량이 많고 손이 많이 가는 작업인 만큼 시간이 많이 소요 될 것 같아 선택과 집중이 필요하다고 생각되어집니다.

 그래서 저는 저희 팀이 이번에 zulip 기여방안을 번역과 코드리뷰로 정했지만 코드리뷰는 포기하고 번역에 집중하는 것이 좋아보이는데 다른 분들은 어떻게 생각하시나요?

**Comment by ddjddd** [comment]
1. 스타일 가이드 확립 -> zulip official docu가 될 수 있도록? 
2. 약간의 번역작업
으로 나누서 진행하면 좋을거 같네요

**Comment by measo3** [comment]
저도 번역작업을 집중적으로 하는거 동의합니다

**Comment by eunjeung** [comment]
번역 작업으로 집중하는게 좋을 것 같습니다.

**Comment by NohYeonJeong** [comment]
저도 번역 작업에 집중하는 것에 동의합니다.

**Comment by L2zz** [comment]
넵 그러면 번역에 집중하기로 하고 review는 제외하도록 하겠습니다.
