### ISSUE TITLE
[Terms] 숫자 관련해서 질문

### ISSUE THREAD

**Issue by eunjeung** [18-2-SKKU-OSS/2018-2-OSS-L5#50]
숫자와 글자가 있을 때 띄워야하는지 붙여야하는지 같은 가이드가 필요할 것 같아요 (ex. 1 시간 or 1시간)
저번 회의 때 말이 나왔던 것 같은데 어떤걸로 정해졌었는지 아시는분 계신가요?

**Comment by L2zz** [comment]
원문을 따라주세요!
