### ISSUE TITLE
[Phrases] subscribe 관련해서 질문

### ISSUE THREAD

**Issue by eunjeung** [18-2-SKKU-OSS/2018-2-OSS-L5#51]
subscribe 관련해서 구독과 가입 중 결과적으로 어떤 것으로 작성하는게 좋을까요?

**Comment by NohYeonJeong** [comment]
저는 스트림에 '가입하다'라고 생각했는데 '구독하다'라고 번역된 것도 있더라구요. 저도 궁금합니다.

**Comment by measo3** [comment]
구독하다가 맞는거 같아요 가입은 join이라구 보통 할거에요 아마
