### ISSUE TITLE
[Other] you를 어떻게 번역하면 좋을지 의견을 구합니다.

### ISSUE THREAD

**Issue by eunjeung** [18-2-SKKU-OSS/2018-2-OSS-L5#52]
저번 회의 때도 말이 나왔던 것 같은데 
이번에 스타일 가이드를 작성하면서 확실하게 해야될 것 같아서요.
귀하로 해야하는지 당신으로 해야하는지 
아니면 둘 다 적절히 섞어서 지금처럼 해야되는지를 결정해야할 것 같습니다.

**Comment by measo3** [comment]
귀하로 하는게 맞는것 같습니다.

**Comment by eunjeung** [comment]
그렇다면 귀하로 모두 작성하겠습니다 :)
