### ISSUE TITLE
[Phrases] Why not start the conversation?

### ISSUE THREAD

**Issue by L2zz** [18-2-SKKU-OSS/2018-2-OSS-L5#56]
이게 기존 번역으로는 `왜 대화를 시작하지 않으세요?`이렇게 나와있는데 
제안적인 의미로`대화를 시작하시겠습니까?`처럼 제안적인 의미라고 생각됩니다.
다른분들은 어떻게 생각하시나요?

**Comment by NohYeonJeong** [comment]
대화를 시작하시겠습니까?가 적당하다고 생각합니다.

**Comment by measo3** [comment]
직역보다는 해석으로 하는게 맞다고 생각해요

**Comment by eunjeung** [comment]
대화를 시작하시겠습니까? 가 더 자연스러운 것 같네요

**Comment by L2zz** [comment]
넵넵 아래를 사용하겠습니다!
