### ISSUE TITLE
[Terms] collapse

### ISSUE THREAD

**Issue by L2zz** [18-2-SKKU-OSS/2018-2-OSS-L5#57]
https://zulipchat.com/help/collapse-a-message
collapse는 메시지가 길 경우 부분적으로만 보이게 하는 기능입니다.
이를 `축소`, `접기`, `병합` 세개로 번역하고 있는데 적합한 단어가 무엇일까요?

**Comment by eunjeung** [comment]
접기가 적합할 것 같습니다

**Comment by NohYeonJeong** [comment]
저도 접기라고 번역했습니다.

**Comment by L2zz** [comment]
접기 사용하도록 하겠습니다
