### ISSUE TITLE
[Terms] draft

### ISSUE THREAD

**Issue by L2zz** [18-2-SKKU-OSS/2018-2-OSS-L5#58]
https://zulipchat.com/help/view-and-edit-your-message-drafts
30일동안 작성 중이던 메시지를 보관해주는 기능으로 보아
`임시 보관함`이나 상황에 따라 `임시 보관`이 적합해 보이는데 기존 번역들은 `초안`과 혼용 되고 있습니다. 
`임시 보관`과 `임시 보관함`으로 통일하고자 하는데 괜찮으신가요?

**Comment by eunjeung** [comment]
네 괜찮을 것 같습니다

**Comment by NohYeonJeong** [comment]
네 동의합니다.

**Comment by L2zz** [comment]
`임시 보관`말고도 `임시 저장`이란 표현도 있습니다

**Comment by eunjeung** [comment]
임시 보관이 좀 더 낫지 않을까요? google gmail에서도 임시보관함이란 표현을 사용하고 있습니다.

**Comment by L2zz** [comment]
임시 보관 사용하겠습니다!
