### ISSUE TITLE
[Terms] people

### ISSUE THREAD

**Issue by L2zz** [18-2-SKKU-OSS/2018-2-OSS-L5#60]
people이 `사용자` 와 `사람`으로 혼용되고 있습니다.
프로그램을 사용하는 사람을 지칭하는 게 일반적이라고 생각되어 `사용자`가 더 적합한 것 같은데
다른 분들은 어떠신가요?

**Comment by eunjeung** [comment]
사용자가 적합할 것 같습니다

**Comment by NohYeonJeong** [comment]
사용자가 더 공식적인 표현인 것 같습니다.

**Comment by measo3** [comment]
저도 문맥적 의미로 봤을때 사용자가 맞는거 같아요

**Comment by L2zz** [comment]
사용자로 사용하겠습니다!
