### ISSUE TITLE
[Terms] missing

### ISSUE THREAD

**Issue by L2zz** [18-2-SKKU-OSS/2018-2-OSS-L5#61]
missing 이 `누락된`으로 해석되는데 
`놓친`이 보다 직관적이고 자주 쓰이는 표현이라고 생각됩니다
다른 분들의 의견은 어떠신가요?

**Comment by eunjeung** [comment]
저는 누락된이 좀 더 맞는 표현인 것 같습니다.
예를 들어 Check if you are missing a space after the command. 라는 문장의 경우 공백이 누락된 건지 아닌지 확인하십시오가 더 자연스러울 것 같아요

**Comment by NohYeonJeong** [comment]
놓친 메시지보다 누락된 메시지가 더 공식적인 표현이지 않을까요?

**Comment by L2zz** [comment]
아 공식성이나 위 문장에대해선느 누락된이 더 적합하긴 하네요!
저는 그 누락된 메시지라는 표현이 전송이 실패한 느낌이 들어서 조금 직관성이 떨어진다고 생각했었습니다.

**Comment by L2zz** [comment]
위 예시들 이랑 저희 룰이 공식적인 표현 사용이니까 누락된 사용하도록 하겠습니다!

**Comment by measo3** [comment]
동의합니다
