### ISSUE TITLE
Review 작업 절차 정하기

### ISSUE THREAD

**Issue by L2zz** [18-2-SKKU-OSS/2018-2-OSS-L5#7]
Transifex의 번역작업은 번역과 그에 대한 확인 작업(review)으로 이루어집니다.

Review 작업 진행 시의 몇가지 절차적인 요소를 정하고자 합니다.

1. 최소 review 인원 
번역에 대한 신뢰성을 주기위해 번역에 대한 최소한의 review 인원을 정하고자 합니다.

2. review 대상
review 대상을 저희 팀원 내부에서 각각의 인원이 review할 대상을 정하고 진행할 지 아니면 위에서 정한 최소 인원을 만족만 한다면 자유롭게 진행할 것인지 정하고자 합니다.

위의 두가지 요소 외에도 논의 할 만한 것들이 있다면 말씀해주시고 의견 부탁드립니다.

**Comment by L2zz** [comment]
1. 최소 인원
 두 명, 자신을 제외한 모든 인원이 확인 할 수 있다면 좋겠지만 이는 상당한 시간이 소요될 것이라고 생각되어 집니다. zulip내부의 필요 번역량과 저희 프로젝트 기간을 고려하면 두 명이상은 불가할 듯 합니다. 

2. review 대상
저희 팀원 내부에서 번역량이 일정하지 않을 것이라 예상되어 reveiw 대상을 정하기 보다는 최소 인원을 만족할 수 있게 자유롭게 review를 하는 것이 바람직해 보입니다.

**Comment by ddjddd** [comment]
일종의 검수 작업을 말씀하시는 건가요?
1. 한 분이 아예 번역을 하지 않고 전부를 검수하는건 어떨까요

**Comment by L2zz** [comment]
Review 작업 절차
기본적으로 모든 인원이 번역과 리뷰에 참여한다.
번역에 어려움이 있을 시 이슈에 올리고 리뷰 요청을 한다 (label: question, project: Translation)
모든 팀원이 이슈에 커멘트 하였을 때 이슈를 연 사람이 확인 후 닫는다.

**Comment by measo3** [comment]
동의합니다.

**Comment by ddjddd** [comment]
네, 확인했습니다.

**Comment by eunjeung** [comment]
확인했습니다.

**Comment by NohYeonJeong** [comment]
확인했습니다.
